# Generated by Django 4.0.4 on 2022-05-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dep1',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep2',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep3',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
    ]
