# Generated by Django 4.0.4 on 2022-05-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_profile_dep1_profile_dep2_profile_dep3'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dep10',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep11',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep12',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep13',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep14',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep15',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep16',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep17',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep18',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep19',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep20',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep21',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep22',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep23',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep24',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep25',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep26',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep27',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep28',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep29',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep30',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep31',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep32',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep4',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep5',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep6',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep7',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep8',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep9',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
    ]
