# Generated by Django 4.0.4 on 2022-05-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_profile_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dep1',
            field=models.ImageField(default='Silueta Insignias.png', upload_to=''),
        ),
    ]
